name: Build & Deploy Server
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: List files
        run: ls

    # steps:
    #   - name: executing remote ssh commands using password
    #     uses: appleboy/ssh-action@v0.1.10
    #     with:
    #       host: ${{ secrets.SSH_HOST }}
    #       key: ${{ secrets.SSH_KEY }}
    #       username: ${{ secrets.SSH_USERNAME }}
    #       paraphrase: ${{ secrets.SSH_PARAPHRASE }}

    #       script: | 
    #         git clone git@github.com:Prasannsitani/ar-menu.git
    #         echo "Clone the repo"


      
      
    #   - uses: actions/checkout@v3
    #   - uses: actions/setup-node@v3
    #     with:
    #       node-version: '14'
    #   - run: npm install -g bats
    #   - run: bats -v
