name: Build & Deploy Server
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configured SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/authorized_keys
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh-keygen -R ${{ secrets.SSH_HOST }}

      - name: List All Droplets
        run: |
          doctl compute droplet list
          doctl compute ssh-key list
          cat ~/.ssh/id_rsa
          cat ~/.ssh/authorized_keys
          cat ~/.ssh/known_hosts
          doctl compute ssh -t=dop_v1_54f857e9bbe40be0f3266144e53738172a5299b7353f6b9e3949853906650827 testing-server

      # - name: Connect to Droplet
      #   run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'Connected to Droplet!'"