name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    # inputs:
    #   db-url:
    #     description: 'Database Url'
    #     default: 'mongodb+srv://admin:admin@ar-menu.jvvucuy.mongodb.net/test'
    #     required: true
    #     type: string
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
