name: Build & Deploy Server
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: List All Droplets
        run: |
          doctl compute droplet list
          doctl compute ssh-key list
        # doctl compute ssh testing-server
        # ls

      # - name: Connect to Droplet
      #   run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'Connected to Droplet!'"
          


      # dop_v1_c9fe14ea5297d2d32c93ed930c0383cd00fb9d2d565e3e4c7a903993747907bf