name: Build & Deploy Server
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Configured SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh-keygen -R ${{ secrets.SSH_HOST }}

      - name: List All Droplets
        run: |
          doctl compute droplet list
          doctl compute ssh-key list
          doctl auth init -t dop_v1_4dd1d8b6fe981402b8894d05f93f4cdd49f5a3251ea536d203f269906e996e5b
          doctl compute ssh -tt testing-server
        # ls

      # - name: Connect to Droplet
      #   run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'Connected to Droplet!'"